# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeffd319d9ee78e78d00d03a6d839b5f38d71e6ce2b52b3eae4ad82372e45e6893e32aa31046e7feaa72dff8202d0ec948b252b8b3fa28b46d2eec1634aa3a0c

test:
  secret_key_base: b15e088b9ce99c573f1d90613e1d49f0ad1ab4476b211e4d921d2b92f9ed115435acb75d2d7abdc9c74b12a0769ec5725da1ab93221a348833f5b38e16819c51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
